In [2]:
import importer
import nsfg
df = nsfg.ReadFemPreg(dct_file='../code/2002FemPreg.dct',
                dat_file='../code/2002FemPreg.dat.gz')
df

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,laborfor_i,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw,totalwgt_lb
0,1,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,8.8125
1,1,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3410.389399,3869.349602,6448.271112,2,9,NaN,7.8750
2,2,1,NaN,NaN,NaN,NaN,5.0,NaN,3.0,5.0,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,9.1250
3,2,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,7.0000
4,2,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,7226.301740,8567.549110,12999.542264,2,12,NaN,6.1875
5,6,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,8.5625
6,6,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,9.5625
7,6,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4870.926435,5325.196999,8874.440799,1,23,NaN,8.3750
8,7,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3409.579565,3787.539000,6911.879921,2,14,NaN,7.5625
9,7,2,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3409.579565,3787.539000,6911.879921,2,14,NaN,6.6250
10,12,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,3612.781968,4146.013572,6909.331618,1,31,NaN,7.8125
11,14,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,7.0000
12,14,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,4.0000
13,14,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,2418.069494,2810.302771,3039.904507,2,56,NaN,NaN
14,15,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,NaN
15,15,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,7.6875
16,15,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,1667.816099,3200.862017,5553.495599,1,33,NaN,7.5000
17,18,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2957.257457,3404.403067,4153.371741,2,14,NaN,6.3125
18,18,2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,2957.257457,3404.403067,4153.371741,2,14,NaN,NaN
19,21,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3408.342437,3965.763949,7237.122630,1,48,NaN,8.7500
20,21,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3408.342437,3965.763949,7237.122630,1,48,NaN,8.1875
21,23,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,6210.373020,8120.841310,13533.382043,2,64,NaN,5.5625
22,23,2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,6210.373020,8120.841310,13533.382043,2,64,NaN,NaN
23,24,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,6.7500
24,24,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,7.3750
25,24,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.573258,4068.628645,7424.840414,1,27,NaN,6.8125
26,28,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3407.794208,3808.343516,6949.846082,2,57,NaN,8.1250
27,31,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,7.1250
28,31,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,6.0625
29,31,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3405.679025,4272.084519,5211.943113,1,2,NaN,7.4375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13563,12547,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3453.545517,6628.022524,11499.619080,1,52,NaN,7.6875
13564,12547,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3453.545517,6628.022524,11499.619080,1,52,NaN,7.6250
13565,12550,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3080.452699,3745.326058,5268.550165,1,79,NaN,8.1250
13566,12551,1,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2418.538866,3653.453268,3951.940400,2,75,NaN,7.5000
13567,12554,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,1914.676604,2177.957240,2764.045534,2,75,NaN,NaN
13568,12554,2,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,0,0,0,1914.676604,2177.957240,2764.045534,2,75,NaN,NaN
13569,12556,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,5.8125
13570,12556,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,6.6875
13571,12556,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,6.0000
13572,12556,4,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2474.619764,3250.573384,3965.699528,1,44,NaN,5.8125
13573,12561,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.089703,2698.650781,4497.301527,1,10,NaN,6.5625
13574,12561,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2418.089703,2698.650781,4497.301527,1,10,NaN,6.1250
13575,12564,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,1820.850938,2129.214067,2768.191208,2,44,NaN,NaN
13576,12565,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3195.641221,3834.241709,6652.409365,1,78,NaN,6.4375
13577,12565,2,35.0,1.0,8.0,NaN,NaN,NaN,NaN,NaN,...,0,0,0,3195.641221,3834.241709,6652.409365,1,78,NaN,NaN
13578,12566,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2080.317155,2422.820274,2627.548587,2,2,NaN,6.0000
13579,12566,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2080.317155,2422.820274,2627.548587,2,2,NaN,7.0000
13580,12568,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,NaN
13581,12568,2,NaN,NaN,NaN,NaN,5.0,NaN,1.0,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,6.3750
13582,12568,3,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,0,0,0,2734.687353,4258.980140,7772.212858,2,28,NaN,NaN
13583,12569,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,2580.967613,2925.167116,5075.164946,2,61,NaN,NaN
13584,12569,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,2580.967613,2925.167116,5075.164946,2,61,NaN,6.3750
13585,12570,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13586,12570,2,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13587,12570,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,5181.311509,6205.829154,11325.017623,2,40,NaN,NaN
13588,12571,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,6.1875
13589,12571,2,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,NaN
13590,12571,3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,NaN
13591,12571,4,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,7.5000
13592,12571,5,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,4670.540953,5795.692880,6269.200989,1,78,NaN,7.5000

In [3]:
df.columns

Index([         u'caseid',        u'pregordr',       u'howpreg_n',
             u'howpreg_p',        u'moscurrp',        u'nowprgdk',
              u'pregend1',        u'pregend2',        u'nbrnaliv',
              u'multbrth',
       ...
            u'laborfor_i',      u'religion_i',         u'metro_i',
               u'basewgt', u'adj_mod_basewgt',        u'finalwgt',
                u'secu_p',            u'sest',         u'cmintvw',
           u'totalwgt_lb'],
      dtype='object', length=244)

In [4]:
import pandas as pd

df.to_csv('data/FemPreg.csv')

In [5]:
df = pd.read_csv('data/FemPreg.csv')

In [6]:
df.describe

<bound method DataFrame.describe of        Unnamed: 0  caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  \
0               0       1         1        NaN        NaN       NaN       NaN
1               1       1         2        NaN        NaN       NaN       NaN
2               2       2         1        NaN        NaN       NaN       NaN
3               3       2         2        NaN        NaN       NaN       NaN
4               4       2         3        NaN        NaN       NaN       NaN
5               5       6         1        NaN        NaN       NaN       NaN
6               6       6         2        NaN        NaN       NaN       NaN
7               7       6         3        NaN        NaN       NaN       NaN
8               8       7         1        NaN        NaN       NaN       NaN
9               9       7         2        NaN        NaN       NaN       NaN
10             10      12         1        NaN        NaN       NaN       NaN
11             11      14         1        NaN        NaN       NaN       NaN
12             12      14         2        NaN        NaN       NaN       NaN
13             13      14         3        NaN        NaN       NaN       NaN
14             14      15         1        NaN        NaN       NaN       NaN
15             15      15         2        NaN        NaN       NaN       NaN
16             16      15         3        NaN        NaN       NaN       NaN
17             17      18         1        NaN        NaN       NaN       NaN
18             18      18         2        NaN        NaN       NaN       NaN
19             19      21         1        NaN        NaN       NaN       NaN
20             20      21         2        NaN        NaN       NaN       NaN
21             21      23         1        NaN        NaN       NaN       NaN
22             22      23         2        NaN        NaN       NaN       NaN
23             23      24         1        NaN        NaN       NaN       NaN
24             24      24         2        NaN        NaN       NaN       NaN
25             25      24         3        NaN        NaN       NaN       NaN
26             26      28         1        NaN        NaN       NaN       NaN
27             27      31         1        NaN        NaN       NaN       NaN
28             28      31         2        NaN        NaN       NaN       NaN
29             29      31         3        NaN        NaN       NaN       NaN
...           ...     ...       ...        ...        ...       ...       ...
13563       13563   12547         2        NaN        NaN       NaN       NaN
13564       13564   12547         3        NaN        NaN       NaN       NaN
13565       13565   12550         1        NaN        NaN       NaN       NaN
13566       13566   12551         1        NaN        NaN       NaN       NaN
13567       13567   12554         1        NaN        NaN       NaN       NaN
13568       13568   12554         2        NaN        NaN       NaN       NaN
13569       13569   12556         1        NaN        NaN       NaN       NaN
13570       13570   12556         2        NaN        NaN       NaN       NaN
13571       13571   12556         3        NaN        NaN       NaN       NaN
13572       13572   12556         4        NaN        NaN       NaN       NaN
13573       13573   12561         1        NaN        NaN       NaN       NaN
13574       13574   12561         2        NaN        NaN       NaN       NaN
13575       13575   12564         1        NaN        NaN       NaN       NaN
13576       13576   12565         1        NaN        NaN       NaN       NaN
13577       13577   12565         2       35.0        1.0       8.0       NaN
13578       13578   12566         1        NaN        NaN       NaN       NaN
13579       13579   12566         2        NaN        NaN       NaN       NaN
13580       13580   12568         1        NaN        NaN       NaN       NaN
13581       13581   12568         2        NaN        NaN       NaN       NaN
13582       13582   12568         3        NaN        NaN       NaN       NaN
13583       13583   12569         1        NaN        NaN       NaN       NaN
13584       13584   12569         2        NaN        NaN       NaN       NaN
13585       13585   12570         1        NaN        NaN       NaN       NaN
13586       13586   12570         2        NaN        NaN       NaN       NaN
13587       13587   12570         3        NaN        NaN       NaN       NaN
13588       13588   12571         1        NaN        NaN       NaN       NaN
13589       13589   12571         2        NaN        NaN       NaN       NaN
13590       13590   12571         3        NaN        NaN       NaN       NaN
13591       13591   12571         4        NaN        NaN       NaN       NaN
13592       13592   12571         5        NaN        NaN       NaN       NaN

       pregend1  pregend2  nbrnaliv     ...       laborfor_i  religion_i  \
0           6.0       NaN       1.0     ...                0           0
1           6.0       NaN       1.0     ...                0           0
2           5.0       NaN       3.0     ...                0           0
3           6.0       NaN       1.0     ...                0           0
4           6.0       NaN       1.0     ...                0           0
5           6.0       NaN       1.0     ...                0           0
6           6.0       NaN       1.0     ...                0           0
7           6.0       NaN       1.0     ...                0           0
8           5.0       NaN       1.0     ...                0           0
9           5.0       NaN       1.0     ...                0           0
10          5.0       NaN       1.0     ...                0           0
11          6.0       NaN       1.0     ...                0           0
12          6.0       NaN       1.0     ...                0           0
13          3.0       NaN       NaN     ...                0           0
14          1.0       NaN       NaN     ...                0           0
15          6.0       NaN       1.0     ...                0           0
16          6.0       NaN       1.0     ...                0           0
17          5.0       NaN       1.0     ...                0           0
18          1.0       NaN       NaN     ...                0           0
19          6.0       NaN       1.0     ...                0           0
20          6.0       NaN       1.0     ...                0           0
21          6.0       NaN       1.0     ...                0           0
22          1.0       NaN       NaN     ...                0           0
23          6.0       NaN       1.0     ...                0           0
24          6.0       NaN       1.0     ...                0           0
25          6.0       NaN       1.0     ...                0           0
26          6.0       NaN       1.0     ...                0           0
27          6.0       NaN       1.0     ...                0           0
28          6.0       NaN       1.0     ...                0           0
29          6.0       NaN       1.0     ...                0           0
...         ...       ...       ...     ...              ...         ...
13563       6.0       NaN       1.0     ...                0           0
13564       6.0       NaN       1.0     ...                0           0
13565       6.0       NaN       1.0     ...                0           0
13566       5.0       NaN       1.0     ...                0           0
13567       3.0       NaN       NaN     ...                0           0
13568       4.0       NaN       NaN     ...                0           0
13569       6.0       NaN       1.0     ...                0           0
13570       6.0       NaN       1.0     ...                0           0
13571       6.0       NaN       1.0     ...                0           0
13572       6.0       NaN       1.0     ...                0           0
13573       6.0       NaN       1.0     ...                0           0
13574       6.0       NaN       1.0     ...                0           0
13575       3.0       NaN       NaN     ...                0           0
13576       6.0       NaN       1.0     ...                0           0
13577       NaN       NaN       NaN     ...                0           0
13578       6.0       NaN       1.0     ...                0           0
13579       6.0       NaN       1.0     ...                0           0
13580       1.0       NaN       NaN     ...                0           0
13581       5.0       NaN       1.0     ...                0           0
13582       4.0       NaN       NaN     ...                0           0
13583       3.0       NaN       NaN     ...                0           0
13584       6.0       NaN       1.0     ...                0           0
13585       3.0       NaN       NaN     ...                0           0
13586       3.0       NaN       NaN     ...                0           0
13587       3.0       NaN       NaN     ...                0           0
13588       6.0       NaN       1.0     ...                0           0
13589       3.0       NaN       NaN     ...                0           0
13590       3.0       NaN       NaN     ...                0           0
13591       6.0       NaN       1.0     ...                0           0
13592       6.0       NaN       1.0     ...                0           0

       metro_i      basewgt  adj_mod_basewgt      finalwgt  secu_p  sest  \
0            0  3410.389399      3869.349602   6448.271112       2     9
1            0  3410.389399      3869.349602   6448.271112       2     9
2            0  7226.301740      8567.549110  12999.542264       2    12
3            0  7226.301740      8567.549110  12999.542264       2    12
4            0  7226.301740      8567.549110  12999.542264       2    12
5            0  4870.926435      5325.196999   8874.440799       1    23
6            0  4870.926435      5325.196999   8874.440799       1    23
7            0  4870.926435      5325.196999   8874.440799       1    23
8            0  3409.579565      3787.539000   6911.879921       2    14
9            0  3409.579565      3787.539000   6911.879921       2    14
10           0  3612.781968      4146.013572   6909.331618       1    31
11           0  2418.069494      2810.302771   3039.904507       2    56
12           0  2418.069494      2810.302771   3039.904507       2    56
13           0  2418.069494      2810.302771   3039.904507       2    56
14           0  1667.816099      3200.862017   5553.495599       1    33
15           0  1667.816099      3200.862017   5553.495599       1    33
16           0  1667.816099      3200.862017   5553.495599       1    33
17           0  2957.257457      3404.403067   4153.371741       2    14
18           0  2957.257457      3404.403067   4153.371741       2    14
19           0  3408.342437      3965.763949   7237.122630       1    48
20           0  3408.342437      3965.763949   7237.122630       1    48
21           0  6210.373020      8120.841310  13533.382043       2    64
22           0  6210.373020      8120.841310  13533.382043       2    64
23           0  3409.573258      4068.628645   7424.840414       1    27
24           0  3409.573258      4068.628645   7424.840414       1    27
25           0  3409.573258      4068.628645   7424.840414       1    27
26           0  3407.794208      3808.343516   6949.846082       2    57
27           0  3405.679025      4272.084519   5211.943113       1     2
28           0  3405.679025      4272.084519   5211.943113       1     2
29           0  3405.679025      4272.084519   5211.943113       1     2
...        ...          ...              ...           ...     ...   ...
13563        0  3453.545517      6628.022524  11499.619080       1    52
13564        0  3453.545517      6628.022524  11499.619080       1    52
13565        0  3080.452699      3745.326058   5268.550165       1    79
13566        0  2418.538866      3653.453268   3951.940400       2    75
13567        0  1914.676604      2177.957240   2764.045534       2    75
13568        0  1914.676604      2177.957240   2764.045534       2    75
13569        0  2474.619764      3250.573384   3965.699528       1    44
13570        0  2474.619764      3250.573384   3965.699528       1    44
13571        0  2474.619764      3250.573384   3965.699528       1    44
13572        0  2474.619764      3250.573384   3965.699528       1    44
13573        0  2418.089703      2698.650781   4497.301527       1    10
13574        0  2418.089703      2698.650781   4497.301527       1    10
13575        0  1820.850938      2129.214067   2768.191208       2    44
13576        0  3195.641221      3834.241709   6652.409365       1    78
13577        0  3195.641221      3834.241709   6652.409365       1    78
13578        0  2080.317155      2422.820274   2627.548587       2     2
13579        0  2080.317155      2422.820274   2627.548587       2     2
13580        0  2734.687353      4258.980140   7772.212858       2    28
13581        0  2734.687353      4258.980140   7772.212858       2    28
13582        0  2734.687353      4258.980140   7772.212858       2    28
13583        0  2580.967613      2925.167116   5075.164946       2    61
13584        0  2580.967613      2925.167116   5075.164946       2    61
13585        0  5181.311509      6205.829154  11325.017623       2    40
13586        0  5181.311509      6205.829154  11325.017623       2    40
13587        0  5181.311509      6205.829154  11325.017623       2    40
13588        0  4670.540953      5795.692880   6269.200989       1    78
13589        0  4670.540953      5795.692880   6269.200989       1    78
13590        0  4670.540953      5795.692880   6269.200989       1    78
13591        0  4670.540953      5795.692880   6269.200989       1    78
13592        0  4670.540953      5795.692880   6269.200989       1    78

       cmintvw  totalwgt_lb
0          NaN       8.8125
1          NaN       7.8750
2          NaN       9.1250
3          NaN       7.0000
4          NaN       6.1875
5          NaN       8.5625
6          NaN       9.5625
7          NaN       8.3750
8          NaN       7.5625
9          NaN       6.6250
10         NaN       7.8125
11         NaN       7.0000
12         NaN       4.0000
13         NaN          NaN
14         NaN          NaN
15         NaN       7.6875
16         NaN       7.5000
17         NaN       6.3125
18         NaN          NaN
19         NaN       8.7500
20         NaN       8.1875
21         NaN       5.5625
22         NaN          NaN
23         NaN       6.7500
24         NaN       7.3750
25         NaN       6.8125
26         NaN       8.1250
27         NaN       7.1250
28         NaN       6.0625
29         NaN       7.4375
...        ...          ...
13563      NaN       7.6875
13564      NaN       7.6250
13565      NaN       8.1250
13566      NaN       7.5000
13567      NaN          NaN
13568      NaN          NaN
13569      NaN       5.8125
13570      NaN       6.6875
13571      NaN       6.0000
13572      NaN       5.8125
13573      NaN       6.5625
13574      NaN       6.1250
13575      NaN          NaN
13576      NaN       6.4375
13577      NaN          NaN
13578      NaN       6.0000
13579      NaN       7.0000
13580      NaN          NaN
13581      NaN       6.3750
13582      NaN          NaN
13583      NaN          NaN
13584      NaN       6.3750
13585      NaN          NaN
13586      NaN          NaN
13587      NaN          NaN
13588      NaN       6.1875
13589      NaN          NaN
13590      NaN          NaN
13591      NaN       7.5000
13592      NaN       7.5000

[13593 rows x 245 columns]>

In [7]:
pregordr = df['pregordr']
pregordr

0        1
1        2
2        1
3        2
4        3
5        1
6        2
7        3
8        1
9        2
10       1
11       1
12       2
13       3
14       1
15       2
16       3
17       1
18       2
19       1
20       2
21       1
22       2
23       1
24       2
25       3
26       1
27       1
28       2
29       3
        ..
13563    2
13564    3
13565    1
13566    1
13567    1
13568    2
13569    1
13570    2
13571    3
13572    4
13573    1
13574    2
13575    1
13576    1
13577    2
13578    1
13579    2
13580    1
13581    2
13582    3
13583    1
13584    2
13585    1
13586    2
13587    3
13588    1
13589    2
13590    3
13591    4
13592    5
Name: pregordr, dtype: int64

In [8]:
outcome = df['outcome']
outcome_len = outcome.count()
outcome_len

13593

In [9]:
outcome_live_len = df[df['outcome']!=1].outcome.count()
outcome_live_len

4445

In [10]:
#Print value counts for birthord and compare to results published in the codebook
df.birthord.value_counts()

1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: birthord, dtype: int64

In [11]:
# Print value counts for prglngth and compare to results published in the codebook
df.prglngth.value_counts(sort=False)

0       15
8      409
16      44
24      31
32     122
40    1120
48       7
1        9
9      594
17     253
25      15
33      50
41     591
2       78
10     137
18      17
26     117
34      60
42     328
50       2
3      151
11     202
19      34
27       8
35     357
43     148
4      412
12     170
20      18
28      38
36     329
44      46
5      181
13     446
21      37
29      23
37     457
45      10
6      543
14      29
22     147
30     198
38     609
46       1
7      175
15      39
23      12
31      29
39    4744
47       1
Name: prglngth, dtype: int64

In [12]:
#Print value counts for agepreg and compare to results published in the codebook.
df.agepreg.value_counts(sort=True)

22.75    100
21.75     92
20.00     91
18.83     90
21.25     90
21.83     87
18.91     85
20.91     83
21.58     83
22.25     83
20.41     82
20.50     82
21.41     81
23.08     81
19.50     81
24.25     81
20.83     80
18.58     80
20.08     80
18.41     79
24.83     79
19.33     78
23.25     78
19.66     78
21.33     77
23.16     76
20.75     76
19.58     76
21.00     76
19.83     75
        ...
11.75      2
40.75      2
42.58      2
13.58      2
42.75      2
43.16      1
10.33      1
39.33      1
10.91      1
42.41      1
44.08      1
10.83      1
11.41      1
41.33      1
41.83      1
13.16      1
12.91      1
12.08      1
42.25      1
12.75      1
12.25      1
43.91      1
10.50      1
12.50      1
42.16      1
11.50      1
42.33      1
13.33      1
13.08      1
11.08      1
Name: agepreg, dtype: int64

In [13]:
#Compute the mean birthweight.
df.totalwgt_lb.mean()

7.265628457623368

In [14]:
#Create a new column named <tt>totalwgt_kg</tt> that contains birth weight in kilograms.  Compute its mean.  Remember that when you create a new column, you have to use dictionary syntax, not dot notation.
df['totalwgt_kg'] = df['totalwgt_lb']*0.453592
df.totalwgt_kg.mean()

3.2956309433503437

In [15]:
#Use a boolean Series to select the records for the pregnancies that ended in live birth.
live = df[df.outcome == 1]
live.outcome.count()

9148

In [16]:
#Count the number of live births with <tt>birthwgt_lb</tt> between 0 and 5 pounds (including both).  The result should be 1125.
live[(live.birthwgt_lb >= 0) & (live.birthwgt_lb <= 5)].shape[0]

1125

In [17]:
#Count the number of live births with <tt>birthwgt_lb</tt> between 9 and 95 pounds (including both).  The result should be 798 
live[(live.birthwgt_lb >= 9) & (live.birthwgt_lb <= 95)].shape

(798, 246)

In [18]:
# Use <tt>birthord</tt> to select the records for first babies and others.  How many are there of each?
firsts = df[df['birthord']==1]
others = df[df['birthord']>1]
firsts.shape[0],others.shape[0]

(4413, 4735)

In [19]:
# Compute the mean weight for first babies and others.
firsts['totalwgt_lb'].mean()

7.201094430437772

In [20]:
others.totalwgt_lb.mean()

7.325855614973262

In [21]:
# Compute the mean prglngth for first babies and others. Compute the difference in means, expressed in hours
firsts['prglngth'].mean()

38.60095173351461

In [22]:
others['prglngth'].mean()

38.52291446673706

In [23]:
diff = firsts.prglngth.mean() - others.prglngth.mean()
diff

0.07803726677754952

In [24]:
diff*7*24

13.11026081862832